// AUTO-GENERATED by frontend-oracle-design from MODEL.bend (bend -o) — DO NOT EDIT.
function word_to_u32(w) {
  let x = 0;
  for (let i = 0; w.$ === "WCon"; i++) {
    x |= Number(w.head) << i;
    w = w.tail;
  }
  return x >>> 0;
}

function u32_to_word(x) {
  let w = {$: "WNil"};
  for (let i = 31; i >= 0; i--) {
    w = {$: "WCon", head: ((x >>> i) & 1) === 1, tail: w};
  }
  return w;
}

function cmp_new(a, b) {
  return {$: a < b ? "LT"
    : a === b ? "EQ" : "GT"};
}

function nat_divmod(a, b) {
  return b === 0 ? {$: "Tuple", fst: 0, snd: a}
    : {$: "Tuple", fst: Math.trunc(a / b), snd: a % b};
}

function nat_chk(n) {
  if (n > 281474976710655) {
    throw "bend: a Nat past the largest immediate 2^48-1";
  }
  return n;
}

function nat_host(n) {
  const int = typeof n === "bigint" || Number.isInteger(n);
  if (int && n >= 0 && n <= 2 ** 53) {
    return Number(n);
  }
  return { [Symbol.toPrimitive]() { throw "bend: a Nat past the largest immediate 2^48-1"; } };
}

function f32_show(x) {
  if (x !== x) {
    return "nan";
  }
  if (!Number.isFinite(x) || Object.is(x, -0)) {
    return x < 0 ? "-inf"
      : x === 0 ? "-0" : "inf";
  }
  let s = "x";
  for (let p = 1; p <= 9 && f32_round(s) !== x; p += 1) {
    s = String(Number(x.toExponential(p - 1)));
  }
  return s;
}

function f32_bits(x) {
  return new Uint32Array(new Float32Array([x]).buffer)[0];
}

function f32_from_bits(u) {
  return new Float32Array(new Uint32Array([u]).buffer)[0];
}

function f32_read(s) {
  const re = /^\s*[+-]?((\d+\.?\d*|\.\d+)(e[+-]?\d+)?|inf(inity)?|nan)$/i;
  const v = f32_round(s.replace(/inf\w*/i, "Infinity"));
  return re.test(s) ? {$: "Some", value: v} : {$: "None"};
}

const f32_round = function f32_round(s) {
  const d = Number(s);
  const a = Math.abs(d);
  const f = Math.fround(a);
  const g = 2 * a - Math.min(f, 2 ** 128);
  if (g === f || Math.fround(g) !== g || g === Infinity) {
    return Math.sign(d) * f;
  }
  let k = 0;
  while (a * 2 ** k % 1 !== 0) {
    k += 1;
  }
  const [, i, r, e] = /(\d*)\.?(\d*)(?:e([+-]?\d+))?$/i.exec(s);
  const n = Number(e ?? 0) - r.length;
  const x = BigInt(i + r) * 2n ** BigInt(k) * 10n ** BigInt(Math.max(n, 0));
  const y = BigInt(a * 2 ** k) * 10n ** BigInt(Math.max(-n, 0));
  return Math.sign(d) * (x === y || x > y !== g > f ? f : g);
};

function char_new(code) {
  if (code > 0x10FFFF || (code >= 0xD800 && code <= 0xDFFF)) {
    throw "bend: " + code + " is not a Unicode scalar value";
  }
  return String.fromCodePoint(code);
}

// Array
// =====

function array_new(d, v) {
  if (d > 31) {
    throw "bend: an array past the deepest block class 31";
  }
  return Array(2 ** d).fill(v);
}

function array_node(a, b) {
  if (a.length !== b.length) {
    throw "bend: runtime fail-stop";
  }
  return a.concat(b);
}

function array_rmw(a, i, f) {
  const at = i % a.length;
  const old = a[at];
  a[at] = f(old);
  return {$: "Tuple", fst: a, snd: old};
}

// Run
// ===

function run_tail(f, x) {
  return {$: "$JMP", f: f.j?.f === f ? f.j : f, x: [x]};
}

function run_clo(j) {
  const f = (x) => run_loop(j(x));
  f.j = j;
  j.f = f;
  return f;
}

function run_loop(r) {
  while (r !== null && typeof r === "object" && r.$ === "$JMP") {
    r = r.f(...r.x);
  }
  return r;
}

function run_lib(f, n) {
  return (...a) => a.length < n ? run_lib((...b) => f(...a, ...b), n - a.length)
    : f(...a);
}

// Effect
// ======

const $0eff = Object.create(null);

function io_eff(k, run, need) {
  if (k in $0eff) {
    throw new Error("bend: two effects register " + k);
  }
  $0eff[k] = { run, need };
}
// Program
// =======

function $Trust$rank$(_c_0) {
  if (_c_0.$ === "ExitOk") {
    return 0;
  } else if (_c_0.$ === "ExitVerdict") {
    return 1;
  } else if (_c_0.$ === "ExitUsage") {
    return 2;
  } else if (_c_0.$ === "ExitAgent") {
    return 3;
  } else if (_c_0.$ === "ExitEnv") {
    return 4;
  } else if (_c_0.$ === "ExitOddLow") {
    return 5;
  } else {
    return 6;
  }
}

function $Trust$pickCode$(_later_0, _a_0, _b_0) {
  if (_later_0) {
    return _b_0;
  } else {
    return _a_0;
  }
}

function $Trust$worse$(_a_0, _b_0) {
  return $Trust$pickCode$(($Nat$is_gt$(($Trust$rank$(_b_0)), ($Trust$rank$(_a_0)))), _a_0, _b_0);
}

function $Trust$lineIntact$(_l_0) {
  if (_l_0.$ === "LineOk") {
    return true;
  } else if (_l_0.$ === "LineEdited") {
    return false;
  } else if (_l_0.$ === "LineUnlinked") {
    return false;
  } else {
    return false;
  }
}

function $Trust$intact$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return true;
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Bool$and$(($Trust$lineIntact$(_h_0)), ($Trust$intact$(_t_0)));
  }
}

function $Trust$appendLine$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Con", "head": {$: "LineOk"}, "tail": {$: "Nil"}};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return {$: "Con", "head": _h_0, "tail": ($Trust$appendLine$(_t_0))};
  }
}

function $Trust$edited$(_l_0) {
  if (_l_0.$ === "LineOk") {
    return {$: "LineEdited"};
  } else if (_l_0.$ === "LineEdited") {
    return {$: "LineEdited"};
  } else if (_l_0.$ === "LineUnlinked") {
    return {$: "LineEdited"};
  } else {
    return {$: "LineTorn"};
  }
}

function $Trust$unlinked$(_l_0) {
  if (_l_0.$ === "LineOk") {
    return {$: "LineUnlinked"};
  } else if (_l_0.$ === "LineEdited") {
    return {$: "LineEdited"};
  } else if (_l_0.$ === "LineUnlinked") {
    return {$: "LineUnlinked"};
  } else {
    return {$: "LineTorn"};
  }
}

function $Trust$editFirst$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return {$: "Con", "head": ($Trust$edited$(_h_0)), "tail": _t_0};
  }
}

function $Trust$unlinkHead$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return {$: "Con", "head": ($Trust$unlinked$(_h_0)), "tail": _t_0};
  }
}

function $Trust$removeFirst$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _t_0 = _xs_0["tail"];
    return $Trust$unlinkHead$(_t_0);
  }
}

function $Trust$tearCons$(_t_0, _h_0) {
  if (_t_0.$ === "Nil") {
    return {$: "Con", "head": {$: "LineTorn"}, "tail": {$: "Nil"}};
  } else {
    const _h2_0 = _t_0["head"];
    const _t2_0 = _t_0["tail"];
    return {$: "Con", "head": _h_0, "tail": ($Trust$tearCons$(_t2_0, _h2_0))};
  }
}

function $Trust$tearLast$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Trust$tearCons$(_t_0, _h_0);
  }
}

function $Trust$dropCons$(_t_0, _h_0) {
  if (_t_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _h2_0 = _t_0["head"];
    const _t2_0 = _t_0["tail"];
    return {$: "Con", "head": _h_0, "tail": ($Trust$dropCons$(_t2_0, _h2_0))};
  }
}

function $Trust$dropLast$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Nil"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Trust$dropCons$(_t_0, _h_0);
  }
}

function $Trust$tamper$(_xs_0, _how_0) {
  if (_how_0.$ === "EditFirst") {
    return $Trust$editFirst$(_xs_0);
  } else if (_how_0.$ === "RemoveFirst") {
    return $Trust$removeFirst$(_xs_0);
  } else if (_how_0.$ === "TearLast") {
    return $Trust$tearLast$(_xs_0);
  } else {
    return $Trust$dropLast$(_xs_0);
  }
}

function $Trust$envFailed$(_env_0, _agent_0, _retries_0) {
  if (_env_0 === 0) {
    return {$: "Judging", "env": 0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Raised", "cause": {$: "CauseEnv"}}};
  } else {
    const _p_0 = (_env_0 - 1);
    return {$: "Judging", "env": _p_0, "agent": _agent_0, "retries": nat_chk(_retries_0 + 1), "phase": {$: "Attempting"}};
  }
}

function $Trust$agentFailed$(_agent_0, _env_0, _retries_0) {
  if (_agent_0 === 0) {
    return {$: "Judging", "env": _env_0, "agent": 0, "retries": _retries_0, "phase": {$: "Raised", "cause": {$: "CauseAgent"}}};
  } else {
    const _p_0 = (_agent_0 - 1);
    return {$: "Judging", "env": _env_0, "agent": _p_0, "retries": nat_chk(_retries_0 + 1), "phase": {$: "Attempting"}};
  }
}

function $Trust$failedBy$(_env_0, _agent_0, _retries_0, _cause_0) {
  if (_cause_0.$ === "CauseEnv") {
    return $Trust$envFailed$(_env_0, _agent_0, _retries_0);
  } else if (_cause_0.$ === "CauseAgent") {
    return $Trust$agentFailed$(_agent_0, _env_0, _retries_0);
  } else {
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Raised", "cause": {$: "CauseOther"}}};
  }
}

function $Trust$attemptFailed$(_env_0, _agent_0, _retries_0, _phase_0, _cause_0) {
  if (_phase_0.$ === "Attempting") {
    return $Trust$failedBy$(_env_0, _agent_0, _retries_0, _cause_0);
  } else if (_phase_0.$ === "Judged") {
    const _v_0 = _phase_0["as"];
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Judged", "as": _v_0}};
  } else {
    const _c_0 = _phase_0["cause"];
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Raised", "cause": _c_0}};
  }
}

function $Trust$attemptJudged$(_env_0, _agent_0, _retries_0, _phase_0, _v_0) {
  if (_phase_0.$ === "Attempting") {
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Judged", "as": _v_0}};
  } else if (_phase_0.$ === "Judged") {
    const _w_0 = _phase_0["as"];
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Judged", "as": _w_0}};
  } else {
    const _c_0 = _phase_0["cause"];
    return {$: "Judging", "env": _env_0, "agent": _agent_0, "retries": _retries_0, "phase": {$: "Raised", "cause": _c_0}};
  }
}

function $Trust$atBoundary$(_stamp_0, _rerun_0, _next_0) {
  if (_stamp_0.$ === "StampMatches") {
    return _next_0;
  } else if (_stamp_0.$ === "StampDiffers") {
    return {$: "Refused", "rerun": _rerun_0};
  } else {
    return _next_0;
  }
}

function $Trust$consumed$(_phase_0, _stamp_0) {
  if (_phase_0.$ === "AtJudge") {
    return $Trust$atBoundary$(_stamp_0, {$: "RerunAbstract"}, {$: "AtReview"});
  } else if (_phase_0.$ === "AtReview") {
    return $Trust$atBoundary$(_stamp_0, {$: "RerunJudge"}, {$: "Reviewed"});
  } else if (_phase_0.$ === "Reviewed") {
    return {$: "Reviewed"};
  } else {
    const _r_0 = _phase_0["rerun"];
    return {$: "Refused", "rerun": _r_0};
  }
}

function $Trust$init$() {
  return {$: "Idle"};
}

function $Trust$begin$(_p_0) {
  if (_p_0.$ === "PartFold") {
    return {$: "Folding", "worst": {$: "ExitOk"}};
  } else if (_p_0.$ === "PartLedger") {
    return {$: "Ledgering", "lines": {$: "Nil"}};
  } else if (_p_0.$ === "PartJudge") {
    return {$: "Judging", "env": 2, "agent": 1, "retries": 0, "phase": {$: "Attempting"}};
  } else {
    return {$: "Proving", "phase": {$: "AtJudge"}};
  }
}

function $Trust$step$(_s_0, _m_0) {
  if (_s_0.$ === "Idle") {
    if (_m_0.$ === "Begin") {
      const _p_0 = _m_0["part"];
      return $Trust$begin$(_p_0);
    } else {
      return {$: "Idle"};
    }
  } else if (_s_0.$ === "Folding") {
    const _w_0 = _s_0["worst"];
    if (_m_0.$ === "StageExit") {
      const _c_0 = _m_0["code"];
      return {$: "Folding", "worst": ($Trust$worse$(_w_0, _c_0))};
    } else {
      return {$: "Folding", "worst": _w_0};
    }
  } else if (_s_0.$ === "Ledgering") {
    const _xs_0 = _s_0["lines"];
    if (_m_0.$ === "Append") {
      return {$: "Ledgering", "lines": ($Trust$appendLine$(_xs_0))};
    } else if (_m_0.$ === "Tampered") {
      const _how_0 = _m_0["how"];
      return {$: "Ledgering", "lines": ($Trust$tamper$(_xs_0, _how_0))};
    } else {
      return {$: "Ledgering", "lines": _xs_0};
    }
  } else if (_s_0.$ === "Judging") {
    const _e_0 = _s_0["env"];
    const _a_0 = _s_0["agent"];
    const _r_0 = _s_0["retries"];
    const _ph_0 = _s_0["phase"];
    if (_m_0.$ === "AttemptFailed") {
      const _c_1 = _m_0["cause"];
      return $Trust$attemptFailed$(_e_0, _a_0, _r_0, _ph_0, _c_1);
    } else if (_m_0.$ === "AttemptJudged") {
      const _v_0 = _m_0["as"];
      return $Trust$attemptJudged$(_e_0, _a_0, _r_0, _ph_0, _v_0);
    } else {
      return {$: "Judging", "env": _e_0, "agent": _a_0, "retries": _r_0, "phase": _ph_0};
    }
  } else {
    const _ph_1 = _s_0["phase"];
    if (_m_0.$ === "Consumed") {
      const _st_0 = _m_0["stamp"];
      return {$: "Proving", "phase": ($Trust$consumed$(_ph_1, _st_0))};
    } else {
      return {$: "Proving", "phase": _ph_1};
    }
  }
}

function $Trust$observe$(_s_0) {
  if (_s_0.$ === "Idle") {
    return {$: "ObsIdle"};
  } else if (_s_0.$ === "Folding") {
    const _w_0 = _s_0["worst"];
    return {$: "ObsExit", "code": _w_0};
  } else if (_s_0.$ === "Ledgering") {
    const _xs_0 = _s_0["lines"];
    return {$: "ObsChain", "intact": ($Trust$intact$(_xs_0))};
  } else if (_s_0.$ === "Judging") {
    const _r_0 = _s_0["retries"];
    const _ph_0 = _s_0["phase"];
    return {$: "ObsJudge", "retries": _r_0, "phase": _ph_0};
  } else {
    const _ph_1 = _s_0["phase"];
    return {$: "ObsStamp", "phase": _ph_1};
  }
}

function $Trust$run$($0, $1) {
  for (;;) {
    {
      const _ms_0 = $0;
      const _s_0 = $1;
      if (_ms_0.$ === "Nil") {
        return _s_0;
      } else {
        const _m_0 = _ms_0["head"];
        const _rest_0 = _ms_0["tail"];
        $0 = _rest_0;
        $1 = ($Trust$step$(_s_0, _m_0));
        continue;
      }
    }
  }
}

function $Trust$allExits$() {
  return {$: "Con", "head": {$: "StageExit", "code": {$: "ExitOk"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitVerdict"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitUsage"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitAgent"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitEnv"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitOddLow"}}, "tail": {$: "Con", "head": {$: "StageExit", "code": {$: "ExitOddHigh"}}, "tail": {$: "Nil"}}}}}}}};
}

function $Trust$when$(_ok_0, _m_0, _rest_0) {
  if (_ok_0) {
    return {$: "Con", "head": _m_0, "tail": _rest_0};
  } else {
    return _rest_0;
  }
}

function $Trust$isTorn$(_l_0) {
  if (_l_0.$ === "LineOk") {
    return false;
  } else if (_l_0.$ === "LineEdited") {
    return false;
  } else if (_l_0.$ === "LineUnlinked") {
    return false;
  } else {
    return true;
  }
}

function $Trust$lastTorn$($0, $1) {
  for (;;) {
    {
      const _t_0 = $0;
      const _h_0 = $1;
      if (_t_0.$ === "Nil") {
        return $Trust$isTorn$(_h_0);
      } else {
        const _h2_0 = _t_0["head"];
        const _t2_0 = _t_0["tail"];
        $0 = _t2_0;
        $1 = _h2_0;
        continue;
      }
    }
  }
}

function $Trust$hasTail$(_t_0) {
  if (_t_0.$ === "Nil") {
    return false;
  } else {
    return true;
  }
}

function $Trust$consOffers$(_h_0, _t_0) {
  return {$: "Con", "head": {$: "Append"}, "tail": ($Trust$when$(($Bool$not$(($Trust$isTorn$(_h_0)))), {$: "Tampered", "how": {$: "EditFirst"}}, ($Trust$when$(($Trust$hasTail$(_t_0)), {$: "Tampered", "how": {$: "RemoveFirst"}}, ($Trust$when$(($Bool$not$(($Trust$lastTorn$(_t_0, _h_0)))), {$: "Tampered", "how": {$: "TearLast"}}, {$: "Con", "head": {$: "Tampered", "how": {$: "DropLast"}}, "tail": {$: "Nil"}}))))))};
}

function $Trust$ledgerOffers$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "Con", "head": {$: "Append"}, "tail": {$: "Nil"}};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Trust$consOffers$(_h_0, _t_0);
  }
}

function $Trust$judgeOffers$(_ph_0) {
  if (_ph_0.$ === "Attempting") {
    return {$: "Con", "head": {$: "AttemptFailed", "cause": {$: "CauseEnv"}}, "tail": {$: "Con", "head": {$: "AttemptFailed", "cause": {$: "CauseAgent"}}, "tail": {$: "Con", "head": {$: "AttemptFailed", "cause": {$: "CauseOther"}}, "tail": {$: "Con", "head": {$: "AttemptJudged", "as": {$: "JudgedPass"}}, "tail": {$: "Con", "head": {$: "AttemptJudged", "as": {$: "JudgedManual"}}, "tail": {$: "Con", "head": {$: "AttemptJudged", "as": {$: "JudgedFail"}}, "tail": {$: "Nil"}}}}}}};
  } else if (_ph_0.$ === "Judged") {
    return {$: "Nil"};
  } else {
    return {$: "Nil"};
  }
}

function $Trust$provOffers$(_ph_0) {
  if (_ph_0.$ === "AtJudge") {
    return {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampMatches"}}, "tail": {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampDiffers"}}, "tail": {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampAbsent"}}, "tail": {$: "Nil"}}}};
  } else if (_ph_0.$ === "AtReview") {
    return {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampMatches"}}, "tail": {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampDiffers"}}, "tail": {$: "Con", "head": {$: "Consumed", "stamp": {$: "StampAbsent"}}, "tail": {$: "Nil"}}}};
  } else if (_ph_0.$ === "Reviewed") {
    return {$: "Nil"};
  } else {
    return {$: "Nil"};
  }
}

function $Trust$offers$(_s_0) {
  if (_s_0.$ === "Idle") {
    return {$: "Con", "head": {$: "Begin", "part": {$: "PartFold"}}, "tail": {$: "Con", "head": {$: "Begin", "part": {$: "PartLedger"}}, "tail": {$: "Con", "head": {$: "Begin", "part": {$: "PartJudge"}}, "tail": {$: "Con", "head": {$: "Begin", "part": {$: "PartProvenance"}}, "tail": {$: "Nil"}}}}};
  } else if (_s_0.$ === "Folding") {
    return $Trust$allExits$();
  } else if (_s_0.$ === "Ledgering") {
    const _xs_0 = _s_0["lines"];
    return $Trust$ledgerOffers$(_xs_0);
  } else if (_s_0.$ === "Judging") {
    const _ph_0 = _s_0["phase"];
    return $Trust$judgeOffers$(_ph_0);
  } else {
    const _ph_1 = _s_0["phase"];
    return $Trust$provOffers$(_ph_1);
  }
}

function $Trust$next$(_h_0) {
  return $Trust$offers$(($Trust$run$(_h_0, ($Trust$init$()))));
}

function $Trust$height$(_l_0) {
  if (_l_0.$ === "LayerCli") {
    return 5;
  } else if (_l_0.$ === "LayerPipeline") {
    return 4;
  } else if (_l_0.$ === "LayerInfra") {
    return 3;
  } else if (_l_0.$ === "LayerConfig") {
    return 2;
  } else if (_l_0.$ === "LayerCore") {
    return 1;
  } else {
    return 0;
  }
}

function $Trust$isCore$(_l_0) {
  if (_l_0.$ === "LayerCli") {
    return false;
  } else if (_l_0.$ === "LayerPipeline") {
    return false;
  } else if (_l_0.$ === "LayerInfra") {
    return false;
  } else if (_l_0.$ === "LayerConfig") {
    return false;
  } else if (_l_0.$ === "LayerCore") {
    return true;
  } else {
    return false;
  }
}

function $Trust$isLeaf$(_l_0) {
  if (_l_0.$ === "LayerCli") {
    return false;
  } else if (_l_0.$ === "LayerPipeline") {
    return false;
  } else if (_l_0.$ === "LayerInfra") {
    return false;
  } else if (_l_0.$ === "LayerConfig") {
    return false;
  } else if (_l_0.$ === "LayerCore") {
    return false;
  } else {
    return true;
  }
}

function $Trust$allowed$(_from_0, _to_0) {
  const _x_0 = ($Trust$height$(_to_0));
  const _x_1 = ($Trust$height$(_from_0));
  const _x_2 = ($Bool$and$(($Nat$is_eq$(($Trust$height$(_from_0)), ($Trust$height$(_to_0)))), ($Bool$not$(($Trust$isLeaf$(_from_0))))));
  const _x_3 = ($Bool$and$((_x_0 < _x_1), ($Bool$not$(($Trust$isCore$(_from_0))))));
  return (_x_2 || _x_3);
}

function $Trust$partDecision$(_p_0) {
  if (_p_0.$ === "PartFold") {
    return {$: "DecExitFold"};
  } else if (_p_0.$ === "PartLedger") {
    return {$: "DecLedger"};
  } else if (_p_0.$ === "PartJudge") {
    return {$: "DecJudgeRetry"};
  } else {
    return {$: "DecProvenance"};
  }
}

function $Trust$decisionOf$(_s_0, _m_0) {
  if (_m_0.$ === "Begin") {
    const _p_0 = _m_0["part"];
    return $Trust$partDecision$(_p_0);
  } else if (_m_0.$ === "StageExit") {
    return {$: "DecNone"};
  } else if (_m_0.$ === "Append") {
    return {$: "DecNone"};
  } else if (_m_0.$ === "Tampered") {
    return {$: "DecNone"};
  } else if (_m_0.$ === "AttemptFailed") {
    return {$: "DecNone"};
  } else if (_m_0.$ === "AttemptJudged") {
    return {$: "DecNone"};
  } else {
    return {$: "DecNone"};
  }
}

function $Trust$causeKind$(_c_0) {
  if (_c_0.$ === "CauseEnv") {
    return {$: "AtEnv"};
  } else if (_c_0.$ === "CauseAgent") {
    return {$: "AtAgent"};
  } else {
    return {$: "AtOther"};
  }
}

function $Trust$attemptOf$(_s_0, _m_0) {
  if (_m_0.$ === "Begin") {
    return {$: "AtNone"};
  } else if (_m_0.$ === "StageExit") {
    return {$: "AtNone"};
  } else if (_m_0.$ === "Append") {
    return {$: "AtNone"};
  } else if (_m_0.$ === "Tampered") {
    return {$: "AtNone"};
  } else if (_m_0.$ === "AttemptFailed") {
    const _c_1 = _m_0["cause"];
    return $Trust$causeKind$(_c_1);
  } else if (_m_0.$ === "AttemptJudged") {
    return {$: "AtOk"};
  } else {
    return {$: "AtNone"};
  }
}

function $Trust$stampKind$(_st_0) {
  if (_st_0.$ === "StampMatches") {
    return {$: "StCurrent"};
  } else if (_st_0.$ === "StampDiffers") {
    return {$: "StMismatched"};
  } else {
    return {$: "StAbsent"};
  }
}

function $Trust$stampOf$(_s_0, _m_0) {
  if (_m_0.$ === "Begin") {
    return {$: "StNone"};
  } else if (_m_0.$ === "StageExit") {
    return {$: "StNone"};
  } else if (_m_0.$ === "Append") {
    return {$: "StNone"};
  } else if (_m_0.$ === "Tampered") {
    return {$: "StNone"};
  } else if (_m_0.$ === "AttemptFailed") {
    return {$: "StNone"};
  } else if (_m_0.$ === "AttemptJudged") {
    return {$: "StNone"};
  } else {
    const _st_0 = _m_0["stamp"];
    return $Trust$stampKind$(_st_0);
  }
}

function $Trust$hasTorn$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return false;
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    const _x_0 = ($Trust$isTorn$(_h_0));
    const _x_1 = ($Trust$hasTorn$(_t_0));
    return (_x_0 || _x_1);
  }
}

function $Trust$brokenKind$(_torn_0) {
  if (_torn_0) {
    return {$: "LfTruncated"};
  } else {
    return {$: "LfEdited"};
  }
}

function $Trust$okOrBroken$(_ok_0, _torn_0) {
  if (_ok_0) {
    return {$: "LfValid"};
  } else {
    return $Trust$brokenKind$(_torn_0);
  }
}

function $Trust$nonEmptyKind$(_xs_0) {
  return $Trust$okOrBroken$(($Trust$intact$(_xs_0)), ($Trust$hasTorn$(_xs_0)));
}

function $Trust$fileKind$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "LfAbsent"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Trust$nonEmptyKind$({$: "Con", "head": _h_0, "tail": _t_0});
  }
}

function $Trust$ledgerOf$(_s_0, _m_0) {
  if (_s_0.$ === "Idle") {
    return {$: "LfNone"};
  } else if (_s_0.$ === "Folding") {
    return {$: "LfNone"};
  } else if (_s_0.$ === "Ledgering") {
    const _xs_0 = _s_0["lines"];
    return $Trust$fileKind$(_xs_0);
  } else if (_s_0.$ === "Judging") {
    return {$: "LfNone"};
  } else {
    return {$: "LfNone"};
  }
}

function $Trust$provPhase$(_ph_0) {
  if (_ph_0.$ === "AtJudge") {
    return {$: "PhProvAtJudge"};
  } else if (_ph_0.$ === "AtReview") {
    return {$: "PhProvAtReview"};
  } else if (_ph_0.$ === "Reviewed") {
    return {$: "PhProvReviewed"};
  } else {
    return {$: "PhProvRefused"};
  }
}

function $Trust$raisedPhase$(_c_0) {
  if (_c_0.$ === "CauseEnv") {
    return {$: "PhJudgeFailedEnv"};
  } else if (_c_0.$ === "CauseAgent") {
    return {$: "PhJudgeFailedAgent"};
  } else {
    return {$: "PhJudgeFailedOther"};
  }
}

function $Trust$attemptPhase$(_retries_0) {
  if (_retries_0 === 0) {
    return {$: "PhJudgeFirstAttempt"};
  } else {
    return {$: "PhJudgeRetrying"};
  }
}

function $Trust$judgePhase$(_ph_0, _retries_0) {
  if (_ph_0.$ === "Attempting") {
    return $Trust$attemptPhase$(_retries_0);
  } else if (_ph_0.$ === "Judged") {
    return {$: "PhJudgeCompleted"};
  } else {
    const _c_0 = _ph_0["cause"];
    return $Trust$raisedPhase$(_c_0);
  }
}

function $Trust$intactPhase$(_ok_0) {
  if (_ok_0) {
    return {$: "PhLedgerIntact"};
  } else {
    return {$: "PhLedgerBroken"};
  }
}

function $Trust$ledgerPhase$(_xs_0) {
  if (_xs_0.$ === "Nil") {
    return {$: "PhLedgerEmpty"};
  } else {
    const _h_0 = _xs_0["head"];
    const _t_0 = _xs_0["tail"];
    return $Trust$intactPhase$(($Trust$intact$({$: "Con", "head": _h_0, "tail": _t_0})));
  }
}

function $Trust$phaseOf$(_s_0) {
  if (_s_0.$ === "Idle") {
    return {$: "PhIdle"};
  } else if (_s_0.$ === "Folding") {
    return {$: "PhFolding"};
  } else if (_s_0.$ === "Ledgering") {
    const _xs_0 = _s_0["lines"];
    return $Trust$ledgerPhase$(_xs_0);
  } else if (_s_0.$ === "Judging") {
    const _r_0 = _s_0["retries"];
    const _ph_0 = _s_0["phase"];
    return $Trust$judgePhase$(_ph_0, _r_0);
  } else {
    const _ph_1 = _s_0["phase"];
    return $Trust$provPhase$(_ph_1);
  }
}

function $Trust$beginStep$(_p_0) {
  if (_p_0.$ === "PartFold") {
    return {$: "EvBeginFold"};
  } else if (_p_0.$ === "PartLedger") {
    return {$: "EvBeginLedger"};
  } else if (_p_0.$ === "PartJudge") {
    return {$: "EvBeginJudge"};
  } else {
    return {$: "EvBeginProvenance"};
  }
}

function $Trust$tamperStep$(_h_0) {
  if (_h_0.$ === "EditFirst") {
    return {$: "EvEdit"};
  } else if (_h_0.$ === "RemoveFirst") {
    return {$: "EvRemove"};
  } else if (_h_0.$ === "TearLast") {
    return {$: "EvTear"};
  } else {
    return {$: "EvDrop"};
  }
}

function $Trust$failStep$(_c_0) {
  if (_c_0.$ === "CauseEnv") {
    return {$: "EvFailEnv"};
  } else if (_c_0.$ === "CauseAgent") {
    return {$: "EvFailAgent"};
  } else {
    return {$: "EvFailOther"};
  }
}

function $Trust$judgeStamp$(_st_0) {
  if (_st_0.$ === "StampMatches") {
    return {$: "EvStampMatchAtJudge"};
  } else if (_st_0.$ === "StampDiffers") {
    return {$: "EvStampDiffAtJudge"};
  } else {
    return {$: "EvStampAbsentAtJudge"};
  }
}

function $Trust$reviewStamp$(_st_0) {
  if (_st_0.$ === "StampMatches") {
    return {$: "EvStampMatchAtReview"};
  } else if (_st_0.$ === "StampDiffers") {
    return {$: "EvStampDiffAtReview"};
  } else {
    return {$: "EvStampAbsentAtReview"};
  }
}

function $Trust$stampStep$(_ph_0, _st_0) {
  if (_ph_0.$ === "AtJudge") {
    return $Trust$judgeStamp$(_st_0);
  } else if (_ph_0.$ === "AtReview") {
    return $Trust$reviewStamp$(_st_0);
  } else if (_ph_0.$ === "Reviewed") {
    return {$: "EvOther"};
  } else {
    return {$: "EvOther"};
  }
}

function $Trust$consumedStep$(_s_0, _st_0) {
  if (_s_0.$ === "Idle") {
    return {$: "EvOther"};
  } else if (_s_0.$ === "Folding") {
    return {$: "EvOther"};
  } else if (_s_0.$ === "Ledgering") {
    return {$: "EvOther"};
  } else if (_s_0.$ === "Judging") {
    return {$: "EvOther"};
  } else {
    const _ph_1 = _s_0["phase"];
    return $Trust$stampStep$(_ph_1, _st_0);
  }
}

function $Trust$stepOf$(_s_0, _m_0) {
  if (_m_0.$ === "Begin") {
    const _p_0 = _m_0["part"];
    return $Trust$beginStep$(_p_0);
  } else if (_m_0.$ === "StageExit") {
    return {$: "EvStageExit"};
  } else if (_m_0.$ === "Append") {
    return {$: "EvAppend"};
  } else if (_m_0.$ === "Tampered") {
    const _h_0 = _m_0["how"];
    return $Trust$tamperStep$(_h_0);
  } else if (_m_0.$ === "AttemptFailed") {
    const _c_1 = _m_0["cause"];
    return $Trust$failStep$(_c_1);
  } else if (_m_0.$ === "AttemptJudged") {
    return {$: "EvJudged"};
  } else {
    const _st_0 = _m_0["stamp"];
    return $Trust$consumedStep$(_s_0, _st_0);
  }
}

function $Nat$is_gt$(_a_0, _b_0) {
  return $Cmp$is_gt$(cmp_new(_a_0, _b_0));
}

function $Bool$and$(_a_0, _b_0) {
  if (!_a_0) {
    return false;
  } else {
    return _b_0;
  }
}

function $Bool$not$(_b_0) {
  if (!_b_0) {
    return true;
  } else {
    return false;
  }
}

function $Nat$is_eq$(_a_0, _b_0) {
  return $Cmp$is_eq$(cmp_new(_a_0, _b_0));
}

function $Cmp$is_gt$(_c_0) {
  if (_c_0.$ === "GT") {
    return true;
  } else {
    return false;
  }
}

function $Cmp$is_eq$(_c_0) {
  if (_c_0.$ === "EQ") {
    return true;
  } else {
    return false;
  }
}

function $0m0(v) {
  const top = [v];
  for (let at = top, key = 0;;) {
    switch (v.$) {
      case "Idle": at[key] = v; return top[0];
      case "Folding": at[key] = v; return top[0];
      case "Ledgering": at[key] = v; return top[0];
      case "Judging": at = at[key] = {...v, "env": BigInt(v["env"]), "agent": BigInt(v["agent"]), "retries": BigInt(v["retries"])}; return top[0];
      case "Proving": at[key] = v; return top[0];
      default: throw "bend: Trust has no tag " + v?.$ + " (its tags: Idle, Folding, Ledgering, Judging, Proving); a tag names its constructor as the"
      + " loading file sees it, which a later version will make the same"
      + " everywhere (#1105)";
    }
  }
}

function $0m1(v) {
  const top = [v];
  for (let at = top, key = 0;;) {
    switch (v.$) {
      case "Idle": at[key] = v; return top[0];
      case "Folding": at[key] = v; return top[0];
      case "Ledgering": at[key] = v; return top[0];
      case "Judging": at = at[key] = {...v, "env": nat_host(v["env"]), "agent": nat_host(v["agent"]), "retries": nat_host(v["retries"])}; return top[0];
      case "Proving": at[key] = v; return top[0];
      default: throw "bend: Trust has no tag " + v?.$ + " (its tags: Idle, Folding, Ledgering, Judging, Proving); a tag names its constructor as the"
      + " loading file sees it, which a later version will make the same"
      + " everywhere (#1105)";
    }
  }
}

function $0m2(v) {
  const top = [v];
  for (let at = top, key = 0;;) {
    switch (v.$) {
      case "ObsIdle": at[key] = v; return top[0];
      case "ObsExit": at[key] = v; return top[0];
      case "ObsChain": at[key] = v; return top[0];
      case "ObsJudge": at = at[key] = {...v, "retries": BigInt(v["retries"])}; return top[0];
      case "ObsStamp": at[key] = v; return top[0];
      default: throw "bend: Obs has no tag " + v?.$ + " (its tags: ObsIdle, ObsExit, ObsChain, ObsJudge, ObsStamp); a tag names its constructor as the"
      + " loading file sees it, which a later version will make the same"
      + " everywhere (#1105)";
    }
  }
}
export default {
  "Trust.rank": run_lib((a0) => { const r = BigInt(run_loop($Trust$rank$((a0)))); (a0); return r; }, 1),
  "Trust.pickCode": run_lib((a0, a1, a2) => { const r = (run_loop($Trust$pickCode$((a0), (a1), (a2)))); (a0); (a1); (a2); return r; }, 3),
  "Trust.worse": run_lib((a0, a1) => { const r = (run_loop($Trust$worse$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.lineIntact": run_lib((a0) => { const r = (run_loop($Trust$lineIntact$((a0)))); (a0); return r; }, 1),
  "Trust.intact": run_lib((a0) => { const r = (run_loop($Trust$intact$((a0)))); (a0); return r; }, 1),
  "Trust.appendLine": run_lib((a0) => { const r = (run_loop($Trust$appendLine$((a0)))); (a0); return r; }, 1),
  "Trust.edited": run_lib((a0) => { const r = (run_loop($Trust$edited$((a0)))); (a0); return r; }, 1),
  "Trust.unlinked": run_lib((a0) => { const r = (run_loop($Trust$unlinked$((a0)))); (a0); return r; }, 1),
  "Trust.editFirst": run_lib((a0) => { const r = (run_loop($Trust$editFirst$((a0)))); (a0); return r; }, 1),
  "Trust.unlinkHead": run_lib((a0) => { const r = (run_loop($Trust$unlinkHead$((a0)))); (a0); return r; }, 1),
  "Trust.removeFirst": run_lib((a0) => { const r = (run_loop($Trust$removeFirst$((a0)))); (a0); return r; }, 1),
  "Trust.tearCons": run_lib((a0, a1) => { const r = (run_loop($Trust$tearCons$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.tearLast": run_lib((a0) => { const r = (run_loop($Trust$tearLast$((a0)))); (a0); return r; }, 1),
  "Trust.dropCons": run_lib((a0, a1) => { const r = (run_loop($Trust$dropCons$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.dropLast": run_lib((a0) => { const r = (run_loop($Trust$dropLast$((a0)))); (a0); return r; }, 1),
  "Trust.tamper": run_lib((a0, a1) => { const r = (run_loop($Trust$tamper$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.envFailed": run_lib((a0, a1, a2) => { const r = $0m0(run_loop($Trust$envFailed$(nat_host(a0), nat_host(a1), nat_host(a2)))); BigInt(a0); BigInt(a1); BigInt(a2); return r; }, 3),
  "Trust.agentFailed": run_lib((a0, a1, a2) => { const r = $0m0(run_loop($Trust$agentFailed$(nat_host(a0), nat_host(a1), nat_host(a2)))); BigInt(a0); BigInt(a1); BigInt(a2); return r; }, 3),
  "Trust.failedBy": run_lib((a0, a1, a2, a3) => { const r = $0m0(run_loop($Trust$failedBy$(nat_host(a0), nat_host(a1), nat_host(a2), (a3)))); BigInt(a0); BigInt(a1); BigInt(a2); (a3); return r; }, 4),
  "Trust.attemptFailed": run_lib((a0, a1, a2, a3, a4) => { const r = $0m0(run_loop($Trust$attemptFailed$(nat_host(a0), nat_host(a1), nat_host(a2), (a3), (a4)))); BigInt(a0); BigInt(a1); BigInt(a2); (a3); (a4); return r; }, 5),
  "Trust.attemptJudged": run_lib((a0, a1, a2, a3, a4) => { const r = $0m0(run_loop($Trust$attemptJudged$(nat_host(a0), nat_host(a1), nat_host(a2), (a3), (a4)))); BigInt(a0); BigInt(a1); BigInt(a2); (a3); (a4); return r; }, 5),
  "Trust.atBoundary": run_lib((a0, a1, a2) => { const r = (run_loop($Trust$atBoundary$((a0), (a1), (a2)))); (a0); (a1); (a2); return r; }, 3),
  "Trust.consumed": run_lib((a0, a1) => { const r = (run_loop($Trust$consumed$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.init": run_lib(() => { const r = $0m0(run_loop($Trust$init$()));  return r; }, 0),
  "Trust.begin": run_lib((a0) => { const r = $0m0(run_loop($Trust$begin$((a0)))); (a0); return r; }, 1),
  "Trust.step": run_lib((a0, a1) => { const r = $0m0(run_loop($Trust$step$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.observe": run_lib((a0) => { const r = $0m2(run_loop($Trust$observe$($0m1(a0)))); $0m0(a0); return r; }, 1),
  "Trust.run": run_lib((a0, a1) => { const r = $0m0(run_loop($Trust$run$((a0), $0m1(a1)))); (a0); $0m0(a1); return r; }, 2),
  "Trust.allExits": run_lib(() => { const r = (run_loop($Trust$allExits$()));  return r; }, 0),
  "Trust.when": run_lib((a0, a1, a2) => { const r = (run_loop($Trust$when$((a0), (a1), (a2)))); (a0); (a1); (a2); return r; }, 3),
  "Trust.isTorn": run_lib((a0) => { const r = (run_loop($Trust$isTorn$((a0)))); (a0); return r; }, 1),
  "Trust.lastTorn": run_lib((a0, a1) => { const r = (run_loop($Trust$lastTorn$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.hasTail": run_lib((a0) => { const r = (run_loop($Trust$hasTail$((a0)))); (a0); return r; }, 1),
  "Trust.consOffers": run_lib((a0, a1) => { const r = (run_loop($Trust$consOffers$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.ledgerOffers": run_lib((a0) => { const r = (run_loop($Trust$ledgerOffers$((a0)))); (a0); return r; }, 1),
  "Trust.judgeOffers": run_lib((a0) => { const r = (run_loop($Trust$judgeOffers$((a0)))); (a0); return r; }, 1),
  "Trust.provOffers": run_lib((a0) => { const r = (run_loop($Trust$provOffers$((a0)))); (a0); return r; }, 1),
  "Trust.offers": run_lib((a0) => { const r = (run_loop($Trust$offers$($0m1(a0)))); $0m0(a0); return r; }, 1),
  "Trust.next": run_lib((a0) => { const r = (run_loop($Trust$next$((a0)))); (a0); return r; }, 1),
  "Trust.height": run_lib((a0) => { const r = BigInt(run_loop($Trust$height$((a0)))); (a0); return r; }, 1),
  "Trust.isCore": run_lib((a0) => { const r = (run_loop($Trust$isCore$((a0)))); (a0); return r; }, 1),
  "Trust.isLeaf": run_lib((a0) => { const r = (run_loop($Trust$isLeaf$((a0)))); (a0); return r; }, 1),
  "Trust.allowed": run_lib((a0, a1) => { const r = (run_loop($Trust$allowed$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.partDecision": run_lib((a0) => { const r = (run_loop($Trust$partDecision$((a0)))); (a0); return r; }, 1),
  "Trust.decisionOf": run_lib((a0, a1) => { const r = (run_loop($Trust$decisionOf$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.causeKind": run_lib((a0) => { const r = (run_loop($Trust$causeKind$((a0)))); (a0); return r; }, 1),
  "Trust.attemptOf": run_lib((a0, a1) => { const r = (run_loop($Trust$attemptOf$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.stampKind": run_lib((a0) => { const r = (run_loop($Trust$stampKind$((a0)))); (a0); return r; }, 1),
  "Trust.stampOf": run_lib((a0, a1) => { const r = (run_loop($Trust$stampOf$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.hasTorn": run_lib((a0) => { const r = (run_loop($Trust$hasTorn$((a0)))); (a0); return r; }, 1),
  "Trust.brokenKind": run_lib((a0) => { const r = (run_loop($Trust$brokenKind$((a0)))); (a0); return r; }, 1),
  "Trust.okOrBroken": run_lib((a0, a1) => { const r = (run_loop($Trust$okOrBroken$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.nonEmptyKind": run_lib((a0) => { const r = (run_loop($Trust$nonEmptyKind$((a0)))); (a0); return r; }, 1),
  "Trust.fileKind": run_lib((a0) => { const r = (run_loop($Trust$fileKind$((a0)))); (a0); return r; }, 1),
  "Trust.ledgerOf": run_lib((a0, a1) => { const r = (run_loop($Trust$ledgerOf$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.provPhase": run_lib((a0) => { const r = (run_loop($Trust$provPhase$((a0)))); (a0); return r; }, 1),
  "Trust.raisedPhase": run_lib((a0) => { const r = (run_loop($Trust$raisedPhase$((a0)))); (a0); return r; }, 1),
  "Trust.attemptPhase": run_lib((a0) => { const r = (run_loop($Trust$attemptPhase$(nat_host(a0)))); BigInt(a0); return r; }, 1),
  "Trust.judgePhase": run_lib((a0, a1) => { const r = (run_loop($Trust$judgePhase$((a0), nat_host(a1)))); (a0); BigInt(a1); return r; }, 2),
  "Trust.intactPhase": run_lib((a0) => { const r = (run_loop($Trust$intactPhase$((a0)))); (a0); return r; }, 1),
  "Trust.ledgerPhase": run_lib((a0) => { const r = (run_loop($Trust$ledgerPhase$((a0)))); (a0); return r; }, 1),
  "Trust.phaseOf": run_lib((a0) => { const r = (run_loop($Trust$phaseOf$($0m1(a0)))); $0m0(a0); return r; }, 1),
  "Trust.beginStep": run_lib((a0) => { const r = (run_loop($Trust$beginStep$((a0)))); (a0); return r; }, 1),
  "Trust.tamperStep": run_lib((a0) => { const r = (run_loop($Trust$tamperStep$((a0)))); (a0); return r; }, 1),
  "Trust.failStep": run_lib((a0) => { const r = (run_loop($Trust$failStep$((a0)))); (a0); return r; }, 1),
  "Trust.judgeStamp": run_lib((a0) => { const r = (run_loop($Trust$judgeStamp$((a0)))); (a0); return r; }, 1),
  "Trust.reviewStamp": run_lib((a0) => { const r = (run_loop($Trust$reviewStamp$((a0)))); (a0); return r; }, 1),
  "Trust.stampStep": run_lib((a0, a1) => { const r = (run_loop($Trust$stampStep$((a0), (a1)))); (a0); (a1); return r; }, 2),
  "Trust.consumedStep": run_lib((a0, a1) => { const r = (run_loop($Trust$consumedStep$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
  "Trust.stepOf": run_lib((a0, a1) => { const r = (run_loop($Trust$stepOf$($0m1(a0), (a1)))); $0m0(a0); (a1); return r; }, 2),
};
