#!/usr/bin/env node
/**
 * demo — the whole pipeline in two minutes, with nothing installed.
 *
 * Evaluating this tool used to require a staging site, an account on it, and a
 * working agent CLI. This serves the bundled demo app on an ephemeral local
 * port, points a throwaway project at it, and runs spec -> abstract-ai ->
 * judge -> review with QA_AI_ADAPTER=fixture: no model, no credentials, no
 * network. The fixture judge deliberately returns `manual_review`, so a demo
 * run can never be mistaken for a green verdict.
 *
 * Usage:
 *   npx playwright-spec-for-ai-agent demo [--out=<dir>] [--keep]
 */
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { EXIT_ENVIRONMENT, EXIT_VERDICT_FAIL, runMain } from "./errors.mjs";
import { getPackageScriptsDir } from "./hermes-qa-project-config.mjs";

const DEMO_PAGE = "demo";
const SCRIPTS_DIR = getPackageScriptsDir();
const DEMO_APP_DIR = resolve(SCRIPTS_DIR, "..", "examples", "demo-app");

/**
 * `fixtureDir` replays this demo's own recorded agent output for a stage. The
 * abstract-ai stage needs it: the built-in fixture plan is generic, and the
 * abstraction validator (rightly) rejects a plan whose test titles are not in
 * the spec. `note` explains an expected non-zero exit, so the demo never looks
 * broken when a stage fails by design.
 */
const STAGES = [
  { name: "spec", script: "extract-page-e2e-spec.mjs" },
  {
    name: "abstract-ai",
    script: "run-hermes-spec-abstractor.mjs",
    fixtureDir: join(DEMO_APP_DIR, "fixtures"),
  },
  { name: "judge", script: "run-hermes-page-judge.mjs" },
  {
    name: "review",
    script: "run-hermes-judge-review.mjs",
    noteOn: EXIT_VERDICT_FAIL,
    note: "expected offline: the fixture reviewer marks every rubric criterion as `concern` (it read nothing), so the review is flagged and the stage exits 1. A real adapter can approve.",
  },
];

const HELP = `Usage: npx playwright-spec-for-ai-agent demo [options]

  Run spec -> abstract-ai -> judge -> review against the bundled demo app,
  offline, with the fixture adapter. No credentials, no agent CLI, no network.

Options:
  --out=<dir>   Write the throwaway project here (default: a temp directory)
  --keep        Leave the output directory in place for inspection
  --help, -h    Show this help
`;

export function parseDemoArgs(argv = []) {
  const outArg = argv.find(arg => arg.startsWith("--out="));
  return {
    out: outArg ? resolve(outArg.slice("--out=".length).trim()) : "",
    keep: argv.includes("--keep") || Boolean(outArg),
  };
}

/** One page, served for every path: the fixture adapter never browses anyway. */
export async function startDemoServer(root = DEMO_APP_DIR) {
  const html = readFileSync(join(root, "index.html"));
  const server = createServer((_request, response) => {
    response.writeHead(200, { "content-type": "text/html; charset=utf-8" });
    response.end(html);
  });
  await new Promise((resolveListen, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolveListen);
  });
  return {
    url: `http://127.0.0.1:${server.address().port}`,
    close: () => new Promise(done => server.close(done)),
  };
}

export function writeDemoConfig(outDir, baseUrl) {
  const configPath = join(outDir, "playwright-spec-for-ai-agent.config.mjs");
  writeFileSync(
    configPath,
    `// Generated by \`playwright-spec-for-ai-agent demo\`.
export default {
  root: ${JSON.stringify(outDir)},
  paths: {
    specDir: ${JSON.stringify(DEMO_APP_DIR)},
    outputDir: ${JSON.stringify(join(outDir, "__QA__"))},
  },
  pages: {
    ${DEMO_PAGE}: {
      baseUrl: ${JSON.stringify(baseUrl)},
      targetPath: "/dashboard",
      authRequired: false,
    },
  },
};
`
  );
  return configPath;
}

/**
 * A demo must not inherit the operator's real QA environment: an exported
 * QA_OUTPUT_DIR or QA_FIXTURE_DIR would redirect the run out of the sandbox.
 */
function demoEnv(baseUrl) {
  const env = { ...process.env, QA_AI_ADAPTER: "fixture", STAGING_QA_BASE_URL: baseUrl };
  for (const key of [
    "QA_OUTPUT_DIR",
    "DASHBOARD_QA_OUTPUT_DIR",
    "QA_FIXTURE_DIR",
    "QA_RECORD_VIDEO",
    "STAGING_QA_EMAIL",
    "STAGING_QA_PASSWORD",
  ]) {
    delete env[key];
  }
  return env;
}

/**
 * Async spawn, not spawnSync: the demo app is served from *this* process, and
 * spawnSync would freeze its event loop for the whole stage — the judge's
 * reachability preflight would then time out against a server that is running.
 */
function runStage(stage, { configPath, outDir, env }) {
  const child = spawn(
    process.execPath,
    [
      join(SCRIPTS_DIR, stage.script),
      `--page=${DEMO_PAGE}`,
      `--config=${configPath}`,
      `--project-root=${outDir}`,
      "--auth-required=false",
      "--non-interactive",
    ],
    {
      stdio: "inherit",
      cwd: outDir,
      env: stage.fixtureDir ? { ...env, QA_FIXTURE_DIR: stage.fixtureDir } : env,
    }
  );
  return new Promise(done => {
    child.on("error", () => done(EXIT_ENVIRONMENT));
    child.on("close", code => done(code ?? EXIT_ENVIRONMENT));
  });
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

/** One line per stage, read back from what it actually wrote. */
export function summarizeStages(qaDir) {
  const spec = readJson(join(qaDir, `${DEMO_PAGE}-qa-spec.json`));
  const livePlan = join(qaDir, `${DEMO_PAGE}-qa-spec-live.md`);
  const judgment = readJson(join(qaDir, `${DEMO_PAGE}-hermes-judgment.json`));
  const review = readJson(join(qaDir, `${DEMO_PAGE}-hermes-judge-review.json`));

  return [
    [
      "spec",
      spec
        ? `${spec.scenarios?.length ?? 0} scenario(s), ${
            spec.scenarios?.reduce(
              (total, scenario) => total + (scenario.tests?.length ?? 0),
              0
            ) ?? 0
          } test(s) parsed from demo.spec.ts`
        : "no spec artifact",
    ],
    [
      "abstract-ai",
      existsSync(livePlan)
        ? `Given/When/Then plan: ${readFileSync(livePlan, "utf8").length} chars`
        : "no live plan",
    ],
    [
      "judge",
      judgment
        ? `${judgment.status ?? "unknown"} — ${judgment.summary ?? ""}`
        : "no judgment",
    ],
    [
      "review",
      review
        ? `${review.overallReview ?? "unknown"} — ${review.summary ?? ""}`
        : "no review",
    ],
  ];
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(HELP);
    return;
  }

  const options = parseDemoArgs(argv);
  const outDir = options.out || mkdtempSync(join(tmpdir(), "qa-demo-"));
  mkdirSync(outDir, { recursive: true });

  const server = await startDemoServer();
  console.log(`Demo app served at ${server.url} (spec: ${DEMO_APP_DIR})`);
  console.log(`Throwaway project: ${outDir}`);
  console.log("Adapter: fixture (offline; no model, no credentials, no network)\n");

  const configPath = writeDemoConfig(outDir, server.url);
  const env = demoEnv(server.url);

  try {
    for (const stage of STAGES) {
      console.log(`--- ${stage.name} ---`);
      const status = await runStage(stage, { configPath, outDir, env });
      if (status !== 0) {
        const note = status === stage.noteOn ? ` — ${stage.note}` : "";
        console.log(`(${stage.name} exited ${status}${note})`);
      }
      console.log("");
    }

    const qaDir = join(outDir, "__QA__");
    console.log("Artifacts:");
    for (const file of existsSync(qaDir) ? readdirSync(qaDir).sort() : []) {
      console.log(`  ${join(relative(process.cwd(), qaDir) || qaDir, file)}`);
    }

    console.log("\nWhat each stage produced:");
    for (const [name, detail] of summarizeStages(qaDir)) {
      console.log(`  ${name.padEnd(12)} ${detail}`);
    }

    console.log(
      [
        "",
        ...(options.keep
          ? [
              `Kept: ${outDir}`,
              `Inspect a verdict: npx playwright-spec-for-ai-agent show --page=${DEMO_PAGE} --config=${configPath}`,
            ]
          : [
              "Output directory removed (pass --keep or --out=<dir> to inspect it).",
            ]),
        "Next: point playwright-spec-for-ai-agent.config.mjs at your own specs and staging origin,",
        "then run `npx playwright-spec-for-ai-agent doctor` — see the quickstart in README.md.",
        "",
      ].join("\n")
    );
  } finally {
    await server.close();
    if (!options.keep) rmSync(outDir, { recursive: true, force: true });
  }
}

const isDirectRun =
  process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (isDirectRun) runMain(main);
